<%@ page trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="cms" uri="http://hybris.com/tld/cmstags" %>

<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="ycommerce" uri="http://hybris.com/tld/ycommercetags" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>

<c:if test="${component.visible}">

    <ul data-trigger="#signedInUserOptionsToggle"
        class="nav__links nav__links--products nav__links--mobile  offcanvasGroup1 collapse in hidden-md hidden-lg">
            <%--Dynamically generated by 'acc.navigation.js"--%>
    </ul>
    <%--            第一層目錄--%>
    <ul class="navbar-nav justify-content-end w-100">
        <c:forEach items="${component.navigationNode.children}" var="childLevel1">
            <li class="nav-item  <c:if test="${not empty childLevel1.children}"> dropdown</c:if>">
                <c:forEach items="${childLevel1.entries}" var="childlink1">
                    <cms:component component="${childlink1.item}"
                                   evaluateRestriction="true"/>
                </c:forEach>
                    <%-- Calculate how many sub columns are needed -- Start --%>
                <c:set var="totalSubNavigationColumns" value="${0}"/>
                <c:set var="hasSubChild" value="false"/>
                <c:forEach items="${childLevel1.children}" var="childLevel2">
                    <c:if test="${not empty childLevel2.children}">
                        <c:set var="hasSubChild" value="true"/>
                        <c:set var="subSectionColumns"
                               value="${fn:length(childLevel2.children)/component.wrapAfter}"/>
                        <c:if test="${subSectionColumns > 1 && fn:length(childLevel2.children)%component.wrapAfter > 0}">
                            <c:set var="subSectionColumns"
                                   value="${subSectionColumns + 1}"/>
                        </c:if>
                        <c:choose>
                            <c:when test="${subSectionColumns > 1}">
                                <c:set var="totalSubNavigationColumns"
                                       value="${totalSubNavigationColumns + subSectionColumns}"/>
                            </c:when>

                            <c:when test="${subSectionColumns < 1}">
                                <c:set var="totalSubNavigationColumns"
                                       value="${totalSubNavigationColumns + 1}"/>
                            </c:when>
                        </c:choose>
                    </c:if>
                </c:forEach>

                <c:if test="${not empty childLevel1.children}">
                <div aria-labelledby="navbarDropdownPortfolio" class="dropdown-menu dropdown-menu-left text-white">
                    <c:choose>
                    <c:when test="${hasSubChild}">
                    <c:forEach items="${childLevel1.children}"
                            var="childLevel2">
                    <c:forEach items="${childLevel2.children}"
                            var="childLevel3"
                            step="${component.wrapAfter}"
                            varStatus="i">
                        <%-- wrap if more than 'component.wrapAfter' rows in one sub column --%>
                    <c:if test="${i.index>=component.wrapAfter}">
                    <c:if test="${!i.first}">
                    </c:if>
                    </c:if>
                    <c:forEach items="${childLevel2.children}"
                            var="childLevel3" begin="${i.index}"
                            end="${i.index + component.wrapAfter - 1}">
                    <c:forEach items="${childLevel3.entries}"
                            var="childlink3">
                        <cms:component component="${childlink3.item}" evaluateRestriction="true"
                                element="" class="nav__link--secondary"/>
                    </c:forEach>
                    </c:forEach>
                    </c:forEach>
                    </c:forEach>
                    </c:when>
                    <c:otherwise>

<%--                        第二層目錄--%>
                    <ul class="sub-navigation-list <c:if test="${not empty childLevel2.title}">has-title</c:if>">
                        <c:forEach items="${childLevel1.children}"
                                   var="childLevel2">
                            <c:forEach items="${childLevel2.entries}"
                                       var="childlink2">
                                <cms:component
                                        component="${childlink2.item}"
                                        evaluateRestriction="true"
                                        element=""
                                        class="nav__link--secondary"/>
                            </c:forEach>
                        </c:forEach>
                    </ul>
                    </c:otherwise>
                    </c:choose>
                </div>
                </c:if>
            </li>
        </c:forEach>

<%--        體驗據點--%>
        <sec:authorize access="hasAnyRole('ROLE_ANONYMOUS')">
            <li class="nav-item">
                <c:if test="${empty hideHeaderLinks}">
                    <ycommerce:testId code="header_StoreFinder_link">
                        <div class="nav-location hidden-xs">
                            <c:url value="/store-finder" var="storeFinderUrl"/>
                                <a  href="${fn:escapeXml(storeFinderUrl)}" class="nav-link text-white px-2">
                                    <spring:theme code="header.link.storeFinder"/>
                            </a>
                        </div>
                    </ycommerce:testId>
                </c:if>
            </li>
        </sec:authorize>
    </ul>

</c:if>
